### ISSUE TITLE
Why don't use a pool or multiple processes to publish?

### ISSUE THREAD

**Issue by dcy** [shopgun/turtle#16]
Hi!
Why don't use a pool or multiple processes to send the message to apns? Every process has one connection.
Will it handle more requests per second if use multiple processes(connections)?

**Comment by jlouis** [comment]
The primary reason for only having a single publisher is mostly because we don't need to push more than 50k RPC calls per second, and I know a single publisher can do that easily. In most systems, the overhead before the transport and after the transport dwarfs the actual transportation by quite a lot. Hence, we kind-of decided a single publisher was fast enough for our use.

**Comment by dcy** [comment]
Hi! @jlouis It is me again.
The code is only having a single process, but the ```Architecture``` of README shows ```multiple publishers may be necessary.``` and ```These maintain a pool of workers which handle incoming messages on a Queue```
It confuse me.
